name: C/C++/CUDA Binary build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-sequential:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make clean 
      run: make clean

    - name: make sequential
      run: make sequential

  build-cuda:
    runs-on: ubuntu-latest

    steps:
    - uses: Jimver/cuda-toolkit@v0.2.11
      id: cuda-toolkit
      with:
        cuda: '12.1.0'

    # - run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"

    # - run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
    - name : infos 
      run: nvcc -V