name: C/C++/CUDA Binary build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make clean 
      run: make clean

    - name: make sequential
      run: make sequential

    # - name: cuda-toolkit
    #    uses: Jimver/cuda-toolkit@v0.2.11
    #   id: cuda-toolkit
    #   with:
    #     cuda: '12.1.0'
    #   run: nvcc -V

    # - name: make parallel
    #   uses: Jimver/cuda-toolkit@v0.2.11
    #   id: cuda-toolkit
    #   with:
    #     cuda: '12.1.0'
    #   run: make parallel